# ¿Qué es la Teoría de la Mente?

Iniciemos nuestra aventura por los confines de la teoría de la mente con los siguientes dos casos: 

(1) Carolina acaba de llegar del supermercado con su hijo de 10 años, Benjamín. Al llegar a su casa, ellos dejan todas sus compras encima de la mesa y luego Benjamin va al baño. Antes de que su hijo vuelva, Carolina guarda en la alacena un juguete recién comprado. ¿Dónde crees que Benjamín irá a buscar el juguete?;

(2) final de la copa del mundo, el reloj marca el final del tiempo reglamentario y Lio Messi se dispone a patear el penal que podría convertir a Argentina en campeona del mundo. El portero necesita adivinar a qué lugar Messi lanzará el balón, él sabe que normalmente la dirección de la mirada de un jugador puede darle una pista sobre el lugar donde el jugador está pensando patear el penal. Sin embargo, también es consciente que Messi tratará de engañarlo mirando hacia el lugar donde no lanzará el balón. El árbitro hace sonar el silbato para patear el penal, Messi corre y está mirando hacia la izquierda del portero ¿A qué lugar se lanzará el portero para atajar el penal? 

Los dos ejemplos relatados arriba constituyen instancias donde el razonamiento sobre estados mentales se desencadena. En el primer caso, si asumimos que Benjamín no vio que su madre guardó el juguete en la alacena y, por lo tanto, desconoce el lugar donde efectivamente está el juguete, deberíamos responder que lo más probable es que él vaya a buscar el juguete encima de la mesa. Benjamín posee una falsa creencia acerca del lugar en donde está el juguete. Esta situación refleja muy bien diferentes hechos que nosotros experimentamos en nuestra vida diaria. Sin embargo, el segundo caso es más difícil de predecir. Aquí estamos en frente de una situación donde ambos jugadores están tratando de engañar y adivinar qué hará su rival con el fin de anotar el gol del campeonato del mundo o de evitarlo. Este ejemplo ilustra muy bien una situación de doble engaño, donde ambos jugadores están razonando estratégicamente sobre los estados mentales del contrincante, lo cual, muy probablemente, hace que la mayor parte de sus recursos cognitivos estén completamente focalizados en resolver el penal a su favor. Estos dos casos no solo nos muestran la versatilidad de situaciones en donde encontramos involucrada a la teoría de la mente, sino también que, dependiendo del caso, hay situaciones que son más demandantes que otras. Pero exactamente ¿Qué es la teoría de la mente?

## Definiendo la Teoría de la Mente

La respuesta a la pregunta de arriba y que también titula este capítulo es probablemente la más importante de todo el libro y a la cual le dedicaré más tiempo, aunque hay que decir que todavía en la actualidad existe debate en los círculos académicos sobre qué es exactamente la teoría de la mente. Primero decir que hay diferentes términos que se utilizan para referirse a esta habilidad tales como teoría de la mente ("*theory of mind*"), lectura de la mente (“*mindreading*”), razonamiento de psicología popular (“*folk psychology*”), psicología de creencia-deseo (“*belief-desire psychology*”) o incluso mentalización (“*mentalizing*”). Si bien cada uno de ellos está asentado en diferentes autores y discusiones, probablemente el término más libre de carga teórica sea el de lectura de la mente (como veremos más adelante en el capítulo 7), aunque podría llevar a ciertos equívocos con “campos paranormales” o “místicos”, la lectura de la mente se basa en un sólido y consistente cuerpo de evidencia científica. A lo largo de este texto, me referiré a esta habilidad cognitiva como teoría de la mente o como lectura de la mente de manera intercambiable.

Pues bien, prácticamente en cualquier libro y artículo científico sobre la lectura de la mente encontraremos la siguiente definición parafraseada de diferentes maneras, pero básicamente entendemos que la teoría de la mente es una habilidad o capacidad mental que permite predecir y explicar el comportamiento de los demás utilizando estados mentales tales como deseos o creencias (Apperly, 2010; Wellman, 2014; 2018).^[Al interior de las ciencias cognitivas, esta definición constata el hecho que las personas en términos prácticos usan los estados mentales para entender, explicar, manipular y predecir el comportamiento de los demás, independientemente del problema filosófico de las “otras mentes” o cómo saber si los otros poseen una mente al igual que la de uno mismo y si, efectivamente, los estados mentales tienen eficacia causal para explicar las acciones de otros. Para propósitos de esta introducción, dicho problema, si bien es central y fundamental para entender a los seres humanos, no es el centro de discusión.] Es una definición relativamente breve pero que es necesaria descomponer, explicar y ejemplificar debido a que será nuestro punto de partida y principal cimiento para el resto de los términos que revisaremos. 

La definición comienza con habilidad o capacidad mental. En el contexto de la psicología cognoscitiva, se tiende a considerar que una habilidad o capacidad cognitiva permite llevar a cabo una extensa variedad de procesos mentales como por ejemplo, pensar abstractamente, adquirir conocimientos, resolver problemas, razonar, aprender de la propia experiencia, entre otras (Flavell, 1999). De este modo, la teoría de la mente es una capacidad mental que permite entender las acciones de los demás desde un punto de vista causal, inferencial y basado en estados mentales. Por ejemplo, si veo que Matías se dirige a la cocina, abre el refrigerador y toma una manzana, yo podría interpretar dicho comportamiento en términos causales, infiriendo estados mentales tales como creencias y deseos: Matías tenía hambre (deseo) y pensaba (creencia) que al interior del refrigerador había comida. Nótese que ambos estados mentales son necesarios para que la conducta de Matías sea causalmente inteligible. Si alguno de los dos estados mentales faltase, el comportamiento del protagonista empezaría a carecer de sentido (por ejemplo, si Matías no creyera que había comida en el refrigerador ¿Por qué habría ido hacia allá?). Aunque es relativamente claro, cabe resaltar que los deseos y las creencias son estados mentales abstractos no directamente observables y que son inferidos (a diferencia de las acciones de personas y animales que son públicamente observables), permitiéndonos entender razonablemente a los individuos (y en muchos casos a los animales) que nos rodean.

Una de las características de los estados mentales es que éstos son breves y específicos a ciertas situaciones, en contraposición a otras características psicológicas como los rasgos, que tienden a ser vistos como más estables en el tiempo, que son poseídos por los sujetos y no dependen de circunstancias particulares. Algunos ejemplos de rasgos son la extroversión (aquellas personas que tienden a ser muy sociables y entablar conversaciones con facilidad) o la responsabilidad (aquellas personas que tienden a planificar, organizar y ejecutar diferentes tareas). De este modo, podemos distinguir en nuestra vida mental, al menos, estados y rasgos psicológicos. La definición de lectura de la mente está explícitamente asociada a los estados mentales y no a la psicología de los rasgos.

El estudio de la teoría de la mente es frecuentemente identificado con la investigación en niños (de hecho la mayor parte de los estudios empíricos se han llevado a cabo con esta población), no obstante, el término “teoría de la mente” fue acuñado en un estudio realizado por los primatólogos David Premack y Guy Woodruff (1978), quienes le mostraron a un chimpancé adulto (llamada Sara) una serie de videos de una persona tratando de resolver diferentes tipos de problemas. De acuerdo a los resultados obtenidos por los autores, éstos concluyeron que el chimpancé adulto fue capaz de atribuir y representar los estados mentales de la persona, entendiendo adecuadamente su propósito y eligiendo las opciones correctas de cada pregunta planteada. Bajo esta interpretación, un chimpancé tiene una teoría de la mente en la medida que es capaz de atribuir estados mentales a sí mismo y a otros. El término “teoría” fue usado por estos autores para recalcar que el agente es capaz de generar un sistema de inferencias no observables (i.e., estados mentales) con el fin de predecir la conducta de un otro o blanco (“*target*”). Esta precisión es relevante porque afecta claramente la denominación del objeto de estudio y de cómo entender esta habilidad para un conjunto de autores venideros.

## La Tarea de Falsa Creencia

Esta conclusión generó una controversia que llevó a diferentes filósofos a analizar los resultados, en donde destacó la crítica efectuada por Daniel Dennett (1978). Él sugirió que para sostener que los chimpancés efectivamente tenían la capacidad de atribuir y representar estados mentales, debían responder una tarea donde ellos tuvieran que distinguir entre un hecho y la falsa creencia de una tercera persona.  A la fecha, la discusión sobre si los chimpancés poseen o no una teoría de la mente todavía no está zanjada (ver referencias) con defensores y detractores, pero, para continuar con nuestra historia, la idea planteada por Dennett fue tomada en cuenta por dos psicólogos del desarrollo, Heinz Wimmer y Josef Perner, quienes diseñaron una tarea que cumplía con los requisitos dispuestos por Dennett. De este modo, nació la ahora clásica tarea de falsa creencia (Wimmer & Perner, 1983), que es considerada el *gold standard* en la investigación de la lectura de la mente con niños.

La tarea de falsa creencia consiste en mostrar a dos protagonistas (generalmente en inglés se les llama Sally y Ann, por esta razón también se conoce como la tarea de Sally y Ann), dos contenedores (frecuentemente se usan una canasta y una caja), y un objeto pequeño, el cual puede ser un juguete o un dulce. La historia se presenta en el siguiente orden: Sally se encuentra jugando sola con un juguete y decide ir al baño. Ella guarda su juguete en la canasta y luego se va del lugar. En ese momento, Ann entra, saca el juguete de la canasta y lo guarda en la caja, para posteriormente también irse del lugar. La historia finaliza con el retorno de Sally quien está enfrente de la canasta y la caja, allí se le pregunta al participante ¿Dónde va a buscar el dulce Sally? El éxito en la tarea consiste en señalar el lugar correcto donde Sally debería ir a buscar su juguete (en este caso, debería indicar la canasta) junto con responder apropiadamente un par de preguntas control de memoria y comprensión de la historia. 

La idea original de Wimmer y Perner (1983) era estudiar a qué edad los niños eran capaces de contestar exitosamente esta tarea. Para esto, aplicaron la tarea a niños de diferentes grupos etarios (3 a 4 años, 4 a 6 años y 6 a 9 años), encontrando que ninguno de los niños entre 3 a 4 años respondió correctamente y que a partir de los 4 años los niños comienzan a tener éxito en la tarea, alcanzando un muy alto porcentaje de respuestas correctas después de los 6 años. De este modo, la idea planteada por el filósofo Daniel Dennet fue ingeniosamente operacionalizada por Wimmer y Perner, quienes interpretaron que los niños alrededor de los 4 años de edad empiezan a representar las creencias de los demás y pueden comenzar a inferir que las conductas de los otros se basan en dichas interpretaciones (es decir, Sally tiene una falsa creencia acerca del lugar donde está su juguete, y por ende va a buscarlo a la canasta) y no en el ordenamiento de las cosas en el mundo (en este caso, el juguete está en la caja). 

Los resultados obtenidos a partir de la tarea de falsa creencia han sido ampliamente replicados en psicología del desarrollo por lo que constituye un efecto que refleja un cambio efectivo en la forma de comprender socialmente el mundo por parte de los niños. De hecho, se han creado tareas similares a la tarea de Sally y Ann donde se evalúa falsas creencias, como por ejemplo la tarea de los Smarties o “*Smarties task*” (Gopnik & Astington, 1988)^[Los “Smarties” son chocolates comunes en países anglosajones (similares a los M &S) y que los niños pueden reconocer fácilmente. En el curso de la tarea, a los niños se les pregunta qué hay al interior de la caja (deberían haber chocolates, por lo que ellos deberían responder que hay “Smarties”). Cuando se abre la caja, ellos se dan cuenta que hay lápices en vez de golosinas. El experimentador en ese momento cierra la caja y prosigue con la tarea. A continuación, entra un nuevo personaje a la historia, quien nunca ha visto el contenido de la caja antes, allí se le pregunta a los niños ¿Qué cree el personaje que hay dentro de la caja? Los niños luego de los 4 años responden “Smarties”, pero sorprendentemente, niños menores y/o que no poseen una comprensión acabada de las falsas creencias, responden que hay lápices, sugiriendo que aún no son capaces de distinguir entre el real estado de cosas y las creencias de otras personas], en la cual también se han replicado los patrones de respuesta de niños menores y mayores de 4 años. Estos hallazgos fueron consolidados por un meta-análisis (Wellman, Cross & Watson, 2001), el cual reunió más de 170 trabajos empíricos con niños de diferentes partes del mundo (aunque latinoamérica estuvo subrepresentada probablemente por su falta de trabajos publicados), refrendando que no importa el formato de presentación de la tarea (uso de videos, viñetas, juguetes, etc.), el idioma hablado, pais de procedencia o el sexo de los niños, éstos exhiben consistentemente una tendencia a fallar a los 3 años y comenzar a lograr pasar la tarea por encima del azar a los 4 años de edad. Además de esta evidencia consolida, hay estudios que muestran que niños con hermanos mayores tienen éxito en tareas de falsa creencia antes que niños sin hermanos (Perner, Ruffman & Leekman, 1994), que estar clasificado dentro de un estatus socioeconómico bajo afecta el dominio de la teoría de la mente (Homes, Black & Miller, 1996), que la frecuencia de conversaciones familiares que usen términos de estados mentales también influye en el éxito de tareas de falsa creencia (Brown, Conelan-McCall & Dunn, 1996).  

¿Estos resultados significan que los niños menores de tres años no tienen una teoría de la mente? ¿Es decir, que son incapaces de entender, al menos de manera muy rudimentaria, que otra persona experimenta estados mentales? Basta con recurrir a nuestra experiencia personal interactuando con niños o incluso con infantes, para darnos cuenta que, lo más probable, es que ellos sí se comportan socialmente de maneras que sugieren que entienden a los demás de manera mentalista. Por ejemplo, un niño de 3 años puede comprender que, si a alguien le gustan los chocolates y no le gustan las zanahorias, probablemente elegirá un chocolate si tiene ganas de comer algo. Este simple razonamiento revela de manera clara que nuestras capacidades de atribuir estados mentales van más allá de las (falsas) creencias. De hecho, hay un número importante de psicólogas y psicólogos del desarrollo durante los últimos 20 años que han estudiado decididamente cómo niños menores de 3 años son capaces de imputar estados mentales, tratando de diseñar ingeniosos experimentos para responder estas preguntas de investigación, sobretodo teniendo en cuenta que los infantes no han adquirido aún lenguaje. Estos esfuerzos han rendido frutos y han hecho modificar profundamente la visión que tenemos de los infantes como seres sociales, dando lugar a debates muy interesantes cuyos resultados serán discutidos en el capítulo 2.

## Teoría de la Mente, Falsa Creencia y Autismo

Volviendo a los hallazgos generados con la tarea de Sally y Ann, a partir de su uso temprano se comenzó a estudiar las respuestas de niños de una variedad de grupos, obteniéndose datos sumamente interesantes para entender las características de algunos trastornos del desarrollo como lo es el trastorno del espectro autista. Brevemente, el trastorno del espectro autista es una condición del neurodesarrollo caracterizado por diferencias en las habilidades de comunicación social, la presencia de comportamientos restrictivos y repetitivos, junto con dificultades en el procesamiento sensorial (APA, 2013). Con el objetivo de entender las relaciones entre este trastorno del neurodesarrollo con la teoría de la mente, destaca especialmente el proyecto realizado por Baron-Cohen, Leslie y Frith (1985), quienes usaron el paradigma diseñado por Wimmer y Perner (1983) y estudiaron los patrones de respuesta de niños con trastorno del espectro autista, niños con síndrome de Down y niños neurotípicos. La idea que tuvieron fue profundizar sobre la hipótesis de que los déficits sociales de niños con autismo podrían ser debido a una carencia de habilidades ligadas a la atribución de estados mentales, independientemente del desarrollo intelectual que ellos tuvieran, es decir, que las disfunciones sociales experimentadas por niños con autismo no estarían vinculadas a problemas intelectuales. De manera muy interesante, los datos desprendidos del estudio confirmaron dicha hipótesis, lo que inauguró una extensa línea de trabajos con niños pertenecientes al espectro autista y su rendimiento en tareas de *mindreading*. 

Estos resultados, junto con otra cantidad de evidencia que se empezaba a acumular, llevaron a varios autores, casi como una consecuencia lógica, a mirar a la capacidad de leer la mente como un mecanismo cognitivo especializado o módulo cognitivo (Baron-Cohen et al.,1985; Baron-Cohen, 1995; Cosmides & Tooby 1994). ¿Qué es un módulo cognitivo? En términos muy simples y resumidos, un módulo es una especialización de un sistema cognitivo que permite resolver problemas muy delimitados (como atribuir estados mentales para entender y predecir las conductas de otros) y, en las versiones más duras, se les suele ver como innatos, automáticos e inconscientes (ver capítulo 4 para matices de estas características). En un conocido ensayo publicado a mediados de los noventa, Baron-Cohen (1995) sostiene que los niños con autismo experimentan una ceguera mental (“*mindblindness*”), es decir, el módulo dedicado a procesar información de la teoría de la mente estaría dañado y, por tal razón, serían incapaces de comprender que las personas son sujetos con mentes. 

Si bien es cierto que los niños con autismo experimentan problemas para ser recíprocos socialmente, esto no significa que el mundo social esté completamente vedado para ellos y no puedan desarrollar entendimiento o competencias sociales. Por ejemplo, existe evidencia que muestra que son capaces de pasar tareas de lectura de la mente a una edad más tardía (citas) y que pueden entender estereotipos de género o basados en la raza (citas). Obviamente, si el mundo social fuera un campo clausurado para ellos, no tendrían forma de entender esta forma de categorización social. En el capítulo 6, se revisa y describe evidencia en relación a la teoría de la mente y el autismo.

## Más Allá de las Falsas Creencias

En los últimos 20 años de investigación en la lectura de la mente, se han elaborado nuevos procedimientos que intentan capturar una amplia variedad de estados mentales presentes en la niñez, los cuales, en algunos casos, incluyen al de falsa creencia. Con este objetivo en mente, Wellman y Liu (2004) construyeron la escala de teoría de la mente (“theory of mind scale”), la cual incluye una variedad de estados mentales en el curso del desarrollo de la niñez y desarrolla la idea de que se van desplegando secuencialmente, y en la medida que un niño es capaz responder correctamente un estado mental más avanzando en la escala, los estados mentales menos avanzados también deberían ser pasados. Esta escala evalúa los siguientes estados mentales: deseos diferentes, creencias diferencias, acceso a conocimiento, falsa creencia y emociones escondidas. Todos estos estados mentales constituyen pasos significativos hacia el desarrollo de la medición, conceptualización y la progresión del razonamiento de ToM. Antes de proporcionar las definiciones de cada uno de ellos, consideremos los siguiente casos para hacer más fácil su comprensión.  

Supongamos que a usted, como a la gran mayoría de las personas que conozco, le gustan los chocolates y que a Marcela no le gustan los chocolates, sino que a ella le encantan las papas fritas pringles, esas que vienen en un envase cilíndrico en diferentes colores según sabor. En la situación que usted tuviera que predecir qué tipo de comida escogería Marcela ¿Cuál cree usted que escogería, el chocolate o la papas fritas? Para seguir con el ejemplo, supongamos que usted cree que las papas fritas se encuentran en el refrigerador y Marcela cree que las papas están en una bolsa cerca de la entrada de su casa. ¿Dónde cree usted que Marcela iría a buscar las papas fritas? Ahora consideremos que yo acabo de guardar las papas fritas en la alacena sin que nadie más me viera ¿Marcela sabe dónde están guardadas las papas fritas? A continuación, pensemos que tomo el envase de papas fritas, saco todas ellas y en su interior pongo lápices de colores, y solo nosotros dos (lector y yo), sabemos esto. Si le pregunto a Marcela qué cree ella que hay dentro, ¿Qué cree usted que diga?.^[Esta es una variación de la tarea de Smarties propuesta por Gopnik y Astington, 1988] Finalmente, supongamos que Marcela abre el envase de papas fritas porque tiene muchas ganas de comérselas y, en cambio, encuentra un set de lápices de colores, las queda mirando por unos segundos y muestra una leve sonrisa  ¿Cómo cree usted que se siente Marcela? ¿Su sonrisa refleja realmente cómo se siente?


Todos los casos expuestos arriba, además de haber irritado mucho a Marcela, ejemplifican en orden los estados mentales propuestos por Wellman y Liu (2004). Estos autores plantearon que el concepto mental de deseo se manifiesta antes que otros conceptos mentales como conocimiento, creencia o emociones escondidas durante la niñez. En base a esto, Wellman y Liu encontraron que los preescolares primero (alrededor de los tres años) comprenden que las personas tienen (a) deseos diferentes, es decir, los niños son capaces de entender que otras personas pueden tener deseos diferentes a los suyos; posteriormente, se desarrolla la conceptualización de (b) creencias diferentes, la cual implica que las personas pueden tener creencias acerca de un determinado estado de cosas diferentes a las propias; en tercer lugar, (c) acceso a conocimiento, el cual está vinculado con la comprensión que una persona puede no saber el estado de cosas sobre una situación determinada que uno sí conoce; (d) falsa creencia, la que se refiere a que alguien puede saber la verdad sobre una situación dada, y que otra persona puede pensar erróneamente algo distinto; y, finalmente, (e) emociones escondidas, la cual está relacionada a la comprensión de que alguien puede sentirse de una manera determinada y mostrar una emoción diferente.

Este patrón de desarrollo secuencial de la comprensión y correcto uso de los estados mentales listados en la escala de lectura de la mente, ha sido consistentemente encontrado con niños de tres a cinco años en Estados Unidos y Australia (Shahaeian, Peterson, Slaughter & Wellman, 2011) y, recientemente, también se ha observado esta trayectoria en niños suecos (Sundqvist, Holmer, Koch, & Heimann, 2018). 

Sin embargo, el patrón que acabamos de enumerar en la progresión de estados mentales puede relacionarse, al menos, de manera bastante gruesa, con niños que viven en países occidentales. Dado que existen variaciones culturales y de estilos de crianza usados en diferentes países del mundo, Wellman y colaboradores (2006) se preguntaron si la secuencia encontrada en niños de países “occidentales” se replicaría en preescolares de culturas tradicionalmente conocidas como “orientales”, en donde existen factores culturales y de interacción distintivos. Para esto, adaptaron al mandarín la escala de teoría de la mente y la aplicaron a pre-escolares chinos que vivían en Beijing. El patrón de respuestas de los niños chinos exhibió una trayectoria de progresión consistente, al igual que en las muestras “occidentales”, pero se observó que hubo una diferencia en la etapa del desarrollo con respecto a los niños occidentales. Específicamente, los niños chinos pasaron antes la tarea de acceso a conocimiento que la tarea de creencias diferentes. Teniendo en cuenta que existe evidencia que los hermanos influyen en el desarrollo del razonamiento de falsa creencia (Perner et al., 1994), los autores consideraron que este último hallazgo pudo estar vinculado a la política pública China de tener solo un hijo por familia. Para descartar esta idea, Shahaeian, Peterson, Slaughter y Wellman (2011) estudiaron el rendimiento de niños iraníes en la escala de ToM, quienes mantienen relaciones sociales interdependientes con familiares y amigos, similares al tipo de relaciones que se da en China. Los resultados encontrados coinciden con la trayectoria de progresión de niños chinos (diferentes creencias después de acceso de conocimiento), lo que excluiría una explicación basada en la interacción entre hermanos. En una línea de resultados similares, además un reciente estudio llevado a cabo por Selcuk, Brink, Ekerim y Wellman (2018) analizó el desempeño de 260 niños turcos en la escala, quienes pertenecían a diferentes niveles socioeconómicos, el cual mostró que éstos también presentaron el patrón de progresión de niños “orientales” (Turquía tradicionalmente es visto como un país que juega un rol de “puente geográfico” entre Europa y Oriente).

La principal explicación que se ha generado para dar cuenta de estas diferencias es la denominada “hipótesis cultural”, la cual se materializa a través de la confrontación entre “individualismo versus colectivismo” (Ames et al., 2001). De acuerdo a esta hipótesis, las sociedades que estimulan un pensamiento autónomo, caracterizado por la estimulación de ideas propias y un pensamiento crítico frente al de los demás, son conceptualizadas como sociedades con valores individualistas u occidentales; por otro lado, las comunidades que promueven el respeto por las reglas, la autoridad, la filiación familiar y la formación de la identidad entorno a los demás, son conocidas como colectivistas u orientales. De esta forma, los contextos culturales que promueven el pensamiento crítico, el énfasis en desarrollar formas de pensar autónomas y originales, desarrollarían la comprensión del concepto de creencia antes que el de conocimiento (por ejemplo, EEUU o Australia); de manera opuesta, aquellos escenarios culturales en los cuales se enfatiza el conocimiento normativo, el respeto por las reglas y por los mayores, estimularía una comprensión temprana del concepto de conocimiento por sobre el de creencia (por ejemplo, China o Irán).

Aunque la mayoría de las investigaciones se han conducido en países occidentales y en los países orientales descritos arriba, existen algunos estudios llevados a cabo con niños latinoamericanos de tres a cinco años. Calero, Salles Semelman y Sigman (2013) estudiaron a niños argentinos de seis a ocho años con una suite computacional, encontrando un patrón de desarrollo similar al “occidental”; mientras que Castro-Menezes, Cruz, Veloso y Brito (2014) analizaron las respuestas de niños brasileños de cuatro a cinco años, utilizando las tareas incluidas en la escala de teoría de la mente y también hallaron la secuencia típica occidental, sin embargo, los análisis estadísticos empleados por estos últimos autores no correspondieron al tipo de escalamiento unidimensional (i.e., análisis Rasch) utilizado por Wellman y Liu (2004) y otros investigadores, por lo que es difícil interpretarlos en la misma dirección. 

Además, en conjunto con un grupo de investigadores de Chile, hemos estado investigando la secuencia de desarrollo en niños chilenos de diferentes estatus socioeconómico, que viven en contextos citadinos y rurales, constatando la misma progresión occidental (Pérez-Zapata, Cuadra, & Valenzuela, en revisión). Aunque sería tentador decir que este patrón de desarrollo se debe al rol que cumple la influencia de la cultura occidental en estos países latinoamericanos, aún faltan más estudios que examinen otros factores más específicos que apelar a un concepto tan amplio como el de cultura. Por ejemplo, sería útil estudiar el rol que cumplen los estilos de crianza al interior de las familias, el tipo de conversaciones que se den al interior de éstas, si incluyen o no el uso de estados mentales, y si se usan apropiadamente para explicar y predecir las acciones de los demás, además del número de hermanos. 

Todos estos estudios realizados a nivel internacional usando la escala de lectura de la mente, muestran una secuencia de desarrollo consistente del entendimiento y uso de estados mentales para predecir las acciones de otros, comenzando con la atribución de deseos y finalizando con la imputación de falsas creencias y emociones escondidas. En conjunto esta evidencia empírica, ha llevado a diferentes autores a sostener que el desarrollo de diferentes etapas de la teoría de la mente sería universal (Avis & Harris, 1991; Callaghan et al., 2005). Pero, ¿A qué se refiere este término? En psicología científica, universal es un etiqueta descriptiva (no explicativa) que caracteriza a un fenómeno como presente en prácticamente todos los casos de un conjunto, y aplicado al caso de mindreading, presente en prácticamente todos los niños, independientemente del grupo cultural o comunidad al que pertenezcan (Wellman et al., 2001). ¿Esto quiere decir que la progresión de hitos cognitivos sigue una secuencia específica determinista? La evidencia disponible no apoya una respuesta afirmativa a esta pregunta, porque hay variaciones en la secuencia en niños de culturas orientales. Es decir, que si bien es plausible sostener una visión universal del desarrollo de la teoría de la mente, hay variaciones en el orden de los hitos, lo que podría estar ligado a características culturales amplias y/o a elementos específicos de las interacciones familiares, donde los niños crecen. Estos y otros factores, aún necesitan recibir cuidadosas consideraciones, además de ser estudiadas empíricamente para determinar qué aspectos están sujetos a una variación a las condiciones socioculturales de los niños.

## Consideraciones Finales

Hasta aquí y priorizando la narración de la historia canónica de la teoría de la mente, he hecho pocos alcances a algunos tópicos que pueden ser considerados relevantes y dignos de discutir. Me gustaría enfocarme, por ahora, en dos elementos: las creencias como principal estado mental a estudiar y la principal forma de interpretación de la evidencia empírica. Al dirigir nuestra atención a los estados mentales que experimentamos, sabemos que no hay solo creencias, existe una amplia variedad de ellos, tales como deseos, intenciones, conocimientos, motivaciones y emociones, como lo deja de manifiesto la última sección que acabamos de revisar. La literatura científica de la lectura de la mente se ha centrado prácticamente en estados epistémicos (es decir, estados relativos a la adquisición de conocimientos de algún tipo) como percepciones (recuerde el conocido dicho “ver para creer”) y sobretodo creencias y falsas creencias. Esto ha hecho avanzar significativamente nuestro entendimiento durante más de 40 años de investigación en la teoría de la mente, pero debemos reconocer que un panorama explicativo exhaustivo debería incluir toda clase de estados mentales para lograr alcanzar una comprensión acabada de esta habilidad. En segundo lugar, hay múltiples formas de interpretar los resultados de los niños usando la tarea de cambio de lugar o falsa creencia. Hasta ahora, sólo hemos mencionado que los niños logran comprender y representar mentalmente que los agentes se comportan a partir de sus estados mentales. Pero está muy lejos de ser la historia completa o la única interpretación teórica de ver estos hallazgos. En el capítulo X, revisaremos diferentes explicaciones sobre cuáles son las razones que le permiten a los niños y, posteriormente, a adolescentes y adultos, atribuir estados mentales para dar sentido a nuestro mundo social.
