--- 
title: "Una Introducción a la Teoría de la Mente"
author: "Daniel Pérez Zapata"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Prefacio {-}

Bienvenidos a esta introducción a la teoría de la mente. Asumo que si has llegado hasta este texto es porque te encuentras interesado en saber de qué se trata esta habilidad, o tal vez lo encontraste por casualidad navegando en la web o en el buscador de Google, de alguna página web o red social en sus diferentes variantes, o quizás ha sido la recomendación de algún amigo o amiga, o simplemente algún profesor universitario te recomendó este libro. Cualquiera que haya sido la circunstancia que te haya hecho estar “aquí”, me pone muy contento. Estoy a punto de contarte algunas cosas sobre la teoría de la mente a las cuales le he dedicado ya algunos años de trabajo de mi vida. He invertido energía, postulaciones a becas ofrecidas por el estado de Chile, conversaciones con colegas, he hecho muchas amistades en este camino, he estudiado en diferentes lugares, conocido, trabajado y publicado conjuntamente con algunas y algunos de los expertos sobre el tema, moviéndome con mi familia de aquí para allá en un recorrido que, ciertamente, no tiene un horizonte de término en el mediano plazo.

Los objetivos que tuve en mente al escribir esta introducción fueron variados. Me gustaría contarte algo sobre ellos antes de que comencemos a revisar los contenidos propiamente tal. Primero, los lectores que tengo en mente son principalmente estudiantes de pregrado (y tal vez de postgrado) en psicología, trabajo social, educación, sociología y ciencias de salud con intereses en conocer más sobre aspectos cognitivos de las personas (y también de algunos animales). Además, he pensado en académicos, académicas o profesores que estén dictando algún curso de o relacionado con aspectos de la psicología del desarrollo, psicología cognitiva o cognición social. Sin embargo, si tu no estás listado en algunos de los posibles públicos objetivos que acabo de mencionar, eso no quiere decir que no puedas leer (y disfrutar) este libro. De igual modo, este texto puede ser útil para un lector curioso, pero con pocos conocimientos previos sobre psicología científica.  

Hace algunos años tuve la suerte de enseñar estos contenidos en cursos de algunas universidades chilenas y siempre experimenté ciertas limitaciones con respecto a la bibliografía utilizada (muchas veces tuve que escribir yo mismo guías de estudio). Si bien existen libros en español (o más precisamente en castellano) que abordan la teoría de la mente, aún son muy pocos y con muchos grados de complejidad (ni hablar de los artículos científicos!), los cuales, muchas veces, no son los más apropiados para estudiantes nóveles de las ciencias sociales, del comportamiento, de la educación y/o de la salud. A grosso modo, esta introducción fue pensada para ser un texto de fácil lectura, aunque será el lector quien pueda decir, en última instancia, si este objetivo fue logrado. La mayoría de los términos utilizados aquí puedan ser entendidos a partir de las explicaciones y ejemplos proporcionados, disminuyendo al mínimo la utilización de otras fuentes para su comprensión. Sin embargo, esto no significa que sea una lectura liviana o haya una ausencia de referencias en el texto. Para el lector interesado en buscar más detalles en fuentes externas, podrá consultar por los textos en la sección de referencias, aunque he tratado de incluir sólo aquellas necesarias con el fin de no entorpecer la fluencia de la lectura. Gran parte de la bibliografía en la teoría de la mente está publicada en inglés, por lo que este escrito también ha sido pensado para acercar toda esta rica y fascinante literatura a un público de habla hispana.

En segundo lugar, y si bien este libro no aspira a convertirse en un texto extenso o en un manual, me gustaría proporcionar una actualización sobre algunos resultados interesantes en diferentes líneas de investigación en la teoría de la mente. Principalmente, quiero contribuir a dar a conocer ciertos temas que están siendo discutidos y activamente investigados hoy en día, y que son sumamente relevantes para el devenir del área, pero que, por múltiples y desconocidas razones para mí, no reciben la atención que a mi juicio deberían tener (como por ejemplo los resultados de investigaciones neurocognitivas que se están llevando a cabo en adolescentes, adultos y adultos mayores).

El tercer objetivo es escribir un libro sobre teoría de la mente que siga la filosofía de acceso abierto, sin murallas de pago y que esté disponible para todo aquel que desee leerlo e informarse sobre esta importante habilidad socio-cognitiva. Creo que una de las principales deudas que tiene el mundo académico, universitario y la comunidad científica (al menos en Chile) tiene que ver con la divulgación del conocimiento y del quehacer mismo de nuestro trabajo diario con respecto al conocimiento que generamos como investigadores. Muchas veces, nos sentimos muy cómodos en el aula de clases, conferencias y congresos, discutiendo con colegas y en publicaciones científicas y nos cuesta salir de las fronteras de la universidad y hacer contacto con el público general. Si bien este libro no es en ninguna medida la respuesta para dichos problemas, al menos aspira a estar disponible, en principio, para todas y todos los interesados. De este modo, espero contribuir a divulgar lo más posible el conocimiento científico acumulado sobre la relevancia de la teoría de la mente en nuestra vida. 

Pero ¿Por qué es importante la teoría de la mente? ¿Por qué debería leer un libro sobre esta capacidad? Como veremos en las páginas que siguen, esta habilidad es fundamental por múltiples motivos, pero me gustaría destacar al menos dos. Primero, la teoría de la mente es una capacidad clave para navegar apropiadamente el mundo social que nos rodea, constituyéndose en un factor clave en la comunicación con los demás (e.g., Grice, 1989; Sperber \& Wilson, 1995). Esta habilidad precisamente nos permite entender lo que alguien está pensando y sintiendo en una situación particular. Es casi tan natural su uso, que prácticamente pasamos por alto su importancia en nuestra vida diaria. Si nuestro razonamiento sobre estados mentales estuviera empobrecido, seguramente tendríamos problemas para entender lo que otros están queriendo comunicar y nuestras respuestas sociales estarían fuera de lugar o serían inapropiadas. Hay numerosos autores que consideran que las personas que sufren algún trastorno psicótico como la esquizofrenia (e.g., Frith, 2004) o alguna variante de trastorno del espectro autista (e.g., Baron-Cohen, 1995), poseen un déficit en sus habilidades de atribución de estados mentales, lo que repercutiría directamente en su comprensión de los fenómenos interpersonales (más detalles en el capítulo 6). 

En segundo lugar, se ha sostenido que la capacidad de “leer otras mentes” es una habilidad única y distintivamente humana (Saxe, 2006). Es decir, que si bien animales como simios, monos e infantes (0 a 2 años) manifiestan habilidades cognitivo-sociales básicas, como por ejemplo, seguimiento de rostros, de cuerpos y de acciones hacia sus congéneres (miembros de la misma especie), incluso entendiendo estados mentales como metas y percepciones, no son capaces de distinguir entre el real estado de cosas en el mundo y la representación que una persona puede tener de dichos estados. Si bien ambos pueden coincidir (el mundo y la representación de éste), también es posible que ambos difieran. La comprensión de esta discrepancia y actuar acordemente, es lo que constituiría poseer una teoría de la mente (ver capítulo 1 para más detalles).


Habiendo explicado los objetivos que perseguía al escribir este libro y por qué es importante estudiar la teoría de la mente, ahora me gustaría describir resumidamente la estructura y los contenidos que encontrarás en las próximas páginas. El capítulo uno describe qué es la teoría de la mente y por qué es importante estudiarla. En este capítulo, me dedico a explicar cada uno de los elementos que componen la definición más ampliamente aceptada de esta capacidad, junto con entregar ejemplos cotidianos para ilustrar con meridiana claridad cada uno de ellos. Al mismo tiempo, explico también qué ideas no forman parte de este objeto de estudio y cuáles son las disciplinas en las cuales “habita”. En el capítulo dos, [definir temas de los próximos capítulos en la medida que vaya escribiendo el capítulo uno].